# Generated by Django 5.2.1 on 2025-05-29 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
                ('package_type', models.CharField(max_length=100)),
                ('download_speed', models.CharField(max_length=50)),
                ('upload_speed', models.CharField(max_length=50)),
                ('datalimit', models.CharField(max_length=50)),
                ('connection_type', models.CharField(max_length=50)),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('setup_fee', models.DecimalField(decimal_places=2, max_digits=8)),
                ('contact_term', models.CharField(choices=[('no', 'No Term'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], max_length=20)),
                ('package_description', models.TextField()),
                ('package_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('upcoming', 'Upcoming')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
