# Generated by Django 5.2.1 on 2025-05-29 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='datalimit',
            new_name='data_limit',
        ),
    ]
