# Generated by Django 5.2.1 on 2025-05-29 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0002_rename_datalimit_package_data_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='data_limit',
            field=models.CharField(choices=[('unlimited', 'Unlimited'), ('100gb', '100 GB'), ('500gb', '500 GB'), ('1tb', '1 TB'), ('2tb', '2 TB')], max_length=50),
        ),
    ]
