# Generated by Django 5.2.1 on 2025-05-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0003_alter_package_data_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='package_type',
            field=models.CharField(choices=[('business', 'Business'), ('student', 'Student'), ('premium', 'Premium'), ('basic', 'Basic')], max_length=100),
        ),
    ]
