# Generated by Django 5.2.1 on 2025-05-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0004_alter_package_package_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='connection_type',
            field=models.CharField(choices=[('Fiber', 'Fiber'), ('DSL', 'DSL'), ('Broadband', 'Broadband')], max_length=50),
        ),
    ]
