# Generated by Django 5.2.1 on 2025-05-29 11:56

import django.utils.timezone
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('company_name', models.CharField(max_length=15)),
                ('business_type', models.CharField(choices=[('isp', 'Internet Service Provider (ISP)'), ('regional_partner', 'Regional Partner'), ('local_distributor', 'Local Distributor'), ('premium_reseller', 'Premium Reseller')])),
                ('registration_number', models.CharField(max_length=15)),
                ('tax_id', models.CharField(max_length=15)),
                ('contact_person', models.CharField(max_length=15)),
                ('position_type', models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('sales_manager', 'Sales Manager'), ('technician', 'Technician'), ('accountant', 'Accountant'), ('customer_support', 'Customer Support'), ('marketing_exec', 'Marketing Executive')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('alternative_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('address', models.TextField(blank=True, max_length=20, null=True)),
                ('services', multiselectfield.db.fields.MultiSelectField(choices=[('sales', 'Sales Support'), ('customer', 'Customer Service'), ('technical', 'Technical Support'), ('billing', 'Billing Management'), ('installation', 'Installation Services'), ('marketing', 'Marketing Support'), ('maintenance', 'Maintenance Services'), ('training', 'Training Programs')], max_length=200)),
                ('notes', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
    ]
