# Generated by Django 5.2.1 on 2025-05-29 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('package', '0005_alter_package_connection_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('alternative_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('prefer_contact_method', models.CharField(choices=[('Phone', 'Phone'), ('Email', 'Email'), ('WhatsApp', 'WhatsApp')], max_length=20)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('connection_type', models.CharField(choices=[('Fiber', 'Fiber'), ('DSL', 'DSL'), ('Broadband', 'Broadband')], max_length=20)),
                ('connection_date', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('account_status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Suspended', 'Suspended')], max_length=20)),
                ('is_billed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='package.package')),
                ('reseller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
