# Generated by Django 5.2.1 on 2025-05-29 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('card', 'Credit/Debit Card'), ('bank', 'Bank Transfer'), ('online', 'Online Payment')], max_length=20)),
                ('payment_date', models.DateField()),
                ('payment_reference', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('complete', 'Complete'), ('pending', 'Pending'), ('failed', 'Failed')], default='complete', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='customer.customer')),
            ],
        ),
    ]
